// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaApuestas.Infrastructure.Persistence;

#nullable disable

namespace SistemaApuestas.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313062404_AgregarMmrSala")]
    partial class AgregarMmrSala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Audit.LogAccion", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Accion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("LogId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("log_acciones", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Audit.Movimiento", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("movimiento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concepto");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("MontoBono")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("monto_bono");

                    b.Property<decimal>("MontoReal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("monto_real");

                    b.Property<int?>("RecargaId")
                        .HasColumnType("integer")
                        .HasColumnName("recarga_id");

                    b.Property<int?>("RetiroId")
                        .HasColumnType("integer")
                        .HasColumnName("retiro_id");

                    b.Property<int?>("SalaId")
                        .HasColumnType("integer")
                        .HasColumnName("sala_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("MovimientoId");

                    b.HasIndex("RecargaId");

                    b.HasIndex("RetiroId");

                    b.HasIndex("SalaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("movimientos", null, t =>
                        {
                            t.HasCheckConstraint("chk_movimiento_origen", "(recarga_id IS NOT NULL AND sala_id IS NULL AND retiro_id IS NULL) OR (recarga_id IS NULL AND sala_id IS NOT NULL AND retiro_id IS NULL) OR (recarga_id IS NULL AND sala_id IS NULL AND retiro_id IS NOT NULL) OR (recarga_id IS NULL AND sala_id IS NULL AND retiro_id IS NULL)");
                        });
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Betting.ParticipanteSala", b =>
                {
                    b.Property<int>("ParticipacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("participacion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParticipacionId"));

                    b.Property<string>("Equipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("equipo");

                    b.Property<bool>("EsCapitan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_capitan");

                    b.Property<int>("GameAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("game_account_id");

                    b.Property<decimal>("PagoConBono")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("pago_con_bono");

                    b.Property<decimal>("PagoConReal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("pago_con_real");

                    b.Property<int>("SalaId")
                        .HasColumnType("integer")
                        .HasColumnName("sala_id");

                    b.Property<int?>("SlotIndex")
                        .HasColumnType("integer")
                        .HasColumnName("slot_index");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("ParticipacionId");

                    b.HasIndex("GameAccountId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SalaId", "SlotIndex")
                        .IsUnique()
                        .HasDatabaseName("uq_sala_slot");

                    b.ToTable("participante_sala", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Betting.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sala_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalaId"));

                    b.Property<int?>("Capitan1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Capitan2Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoEntrada")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_entrada");

                    b.Property<int>("CreadorId")
                        .HasColumnType("integer")
                        .HasColumnName("creador_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ESPERANDO")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GanadorSorteoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GananciaPlataforma")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ganancia_plataforma");

                    b.Property<string>("Juego")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("juego");

                    b.Property<int?>("MapaElegidoId")
                        .HasColumnType("integer")
                        .HasColumnName("mapa_elegido_id");

                    b.Property<int>("MmrMaximo")
                        .HasColumnType("integer");

                    b.Property<int>("MmrMinimo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreLobby")
                        .HasColumnType("text")
                        .HasColumnName("nombrelobby");

                    b.Property<string>("PasswordLobby")
                        .HasColumnType("text")
                        .HasColumnName("passwordlobby");

                    b.Property<decimal>("PremioARepartir")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("premio_a_repartir");

                    b.Property<string>("ResultadoGanador")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resultado_ganador");

                    b.Property<string>("TipoSala")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("BASICA")
                        .HasColumnName("tipo_sala");

                    b.Property<int?>("TorneoId")
                        .HasColumnType("integer")
                        .HasColumnName("torneo_id");

                    b.Property<int?>("TurnoActualId")
                        .HasColumnType("integer");

                    b.Property<string>("VetoLog")
                        .HasColumnType("jsonb")
                        .HasColumnName("veto_log");

                    b.HasKey("SalaId");

                    b.HasIndex("Capitan1Id");

                    b.HasIndex("Capitan2Id");

                    b.HasIndex("CreadorId");

                    b.HasIndex("MapaElegidoId");

                    b.HasIndex("TorneoId");

                    b.ToTable("sala", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Betting.Torneo", b =>
                {
                    b.Property<int>("TorneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("torneo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TorneoId"));

                    b.Property<decimal>("CostoInscripcion")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_inscripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("REGISTRO")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PremioPozo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("premio_pozo");

                    b.HasKey("TorneoId");

                    b.ToTable("torneo", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Financial.SolicitudRecarga", b =>
                {
                    b.Property<int>("RecargaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recarga_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecargaId"));

                    b.Property<int?>("AdminAtendiendoId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_atendiendo_id");

                    b.Property<string>("CuentaDestino")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cuenta_destino");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Metodo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metodo");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("PEN")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NroOperacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nro_operacion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("RecargaId");

                    b.HasIndex("AdminAtendiendoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("solicitud_recarga", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Financial.SolicitudRetiro", b =>
                {
                    b.Property<int>("RetiroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("retiro_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RetiroId"));

                    b.Property<int?>("AdminAtendiendoId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_atendiendo_id");

                    b.Property<string>("CuentaDestino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cuenta_destino");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metodo");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("PEN")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NroOperacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nro_operacion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("RetiroId");

                    b.HasIndex("AdminAtendiendoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("solicitud_retiro", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.Clan", b =>
                {
                    b.Property<int>("ClanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClanId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("ClanId");

                    b.ToTable("clan", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.GameAccount", b =>
                {
                    b.Property<int>("GameAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_account_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameAccountId"));

                    b.Property<bool>("EsRangoManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_rango_manual");

                    b.Property<DateTime>("FechaVinculacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vinculacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_externo");

                    b.Property<string>("IdVisible")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_visible");

                    b.Property<string>("Juego")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("juego");

                    b.Property<string>("RangoActual")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rango_actual");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("GameAccountId");

                    b.HasIndex("UsuarioId", "Juego")
                        .IsUnique()
                        .HasDatabaseName("uq_usuario_juego");

                    b.ToTable("game_account", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.HistorialMmrAdmin", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("historial_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MmrAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("mmr_anterior");

                    b.Property<int>("MmrNuevo")
                        .HasColumnType("integer")
                        .HasColumnName("mmr_nuevo");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("UserStatId")
                        .HasColumnType("integer")
                        .HasColumnName("user_stat_id");

                    b.HasKey("HistorialId");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserStatId");

                    b.ToTable("historial_mmr_admin", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.Mapa", b =>
                {
                    b.Property<int>("MapaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mapa_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MapaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("MapaId");

                    b.ToTable("mapa", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.UsuarioStat", b =>
                {
                    b.Property<int>("UserStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_stat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserStatId"));

                    b.Property<int>("EloMmr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("elo_mmr");

                    b.Property<string>("Juego")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("juego");

                    b.Property<int>("Loses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("loses");

                    b.Property<string>("RangoMedalla")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rango_medalla");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("wins");

                    b.HasKey("UserStatId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuario_stats", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Identity.Baneo", b =>
                {
                    b.Property<int>("BaneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("baneo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BaneoId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("FechaBaneo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baneo")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("Tiempo")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("BaneoId");

                    b.HasIndex("AdminId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("baneo", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Identity.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ap_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ap_paterno");

                    b.Property<int?>("ClanId")
                        .HasColumnType("integer")
                        .HasColumnName("clan_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("PartidasJugadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("partidas_jugadas");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pass_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("USER")
                        .HasColumnName("rol");

                    b.Property<decimal>("SaldoBono")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("saldo_bono");

                    b.Property<decimal>("SaldoReal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("saldo_real");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UsuarioId");

                    b.HasIndex("ClanId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Audit.LogAccion", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Usuario")
                        .WithMany("LogAcciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Audit.Movimiento", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Financial.SolicitudRecarga", "Recarga")
                        .WithMany("Movimientos")
                        .HasForeignKey("RecargaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaApuestas.Domain.Entities.Financial.SolicitudRetiro", "Retiro")
                        .WithMany("Movimientos")
                        .HasForeignKey("RetiroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaApuestas.Domain.Entities.Betting.Sala", "Sala")
                        .WithMany("Movimientos")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recarga");

                    b.Navigation("Retiro");

                    b.Navigation("Sala");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Betting.ParticipanteSala", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Gaming.GameAccount", "GameAccount")
                        .WithMany("Participaciones")
                        .HasForeignKey("GameAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaApuestas.Domain.Entities.Betting.Sala", "Sala")
                        .WithMany("Participantes")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Usuario")
                        .WithMany("Participaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameAccount");

                    b.Navigation("Sala");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Betting.Sala", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Capitan1")
                        .WithMany()
                        .HasForeignKey("Capitan1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Capitan2")
                        .WithMany()
                        .HasForeignKey("Capitan2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Creador")
                        .WithMany("SalasCreadas")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaApuestas.Domain.Entities.Gaming.Mapa", "MapaElegido")
                        .WithMany("Salas")
                        .HasForeignKey("MapaElegidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaApuestas.Domain.Entities.Betting.Torneo", "Torneo")
                        .WithMany("Salas")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Capitan1");

                    b.Navigation("Capitan2");

                    b.Navigation("Creador");

                    b.Navigation("MapaElegido");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Financial.SolicitudRecarga", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "AdminAtendiendo")
                        .WithMany()
                        .HasForeignKey("AdminAtendiendoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Usuario")
                        .WithMany("SolicitudesRecarga")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminAtendiendo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Financial.SolicitudRetiro", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "AdminAtendiendo")
                        .WithMany()
                        .HasForeignKey("AdminAtendiendoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Usuario")
                        .WithMany("SolicitudesRetiro")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminAtendiendo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.GameAccount", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Usuario")
                        .WithMany("GameAccounts")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.HistorialMmrAdmin", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaApuestas.Domain.Entities.Gaming.UsuarioStat", "UsuarioStat")
                        .WithMany("HistorialCambios")
                        .HasForeignKey("UserStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("UsuarioStat");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.UsuarioStat", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Usuario")
                        .WithMany("UsuarioStats")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Identity.Baneo", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Admin")
                        .WithMany("BaneosAplicados")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaApuestas.Domain.Entities.Identity.Usuario", "Usuario")
                        .WithMany("BaneosRecibidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Identity.Usuario", b =>
                {
                    b.HasOne("SistemaApuestas.Domain.Entities.Gaming.Clan", "Clan")
                        .WithMany("Usuarios")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Betting.Sala", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Betting.Torneo", b =>
                {
                    b.Navigation("Salas");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Financial.SolicitudRecarga", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Financial.SolicitudRetiro", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.Clan", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.GameAccount", b =>
                {
                    b.Navigation("Participaciones");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.Mapa", b =>
                {
                    b.Navigation("Salas");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Gaming.UsuarioStat", b =>
                {
                    b.Navigation("HistorialCambios");
                });

            modelBuilder.Entity("SistemaApuestas.Domain.Entities.Identity.Usuario", b =>
                {
                    b.Navigation("BaneosAplicados");

                    b.Navigation("BaneosRecibidos");

                    b.Navigation("GameAccounts");

                    b.Navigation("LogAcciones");

                    b.Navigation("Movimientos");

                    b.Navigation("Participaciones");

                    b.Navigation("SalasCreadas");

                    b.Navigation("SolicitudesRecarga");

                    b.Navigation("SolicitudesRetiro");

                    b.Navigation("UsuarioStats");
                });
#pragma warning restore 612, 618
        }
    }
}
