-- /------------------------------------------------------------------------------------
-- Tabla para los Administradores
CREATE TABLE ADMINISTRADOR (
    ADMINISTRADOR_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
	PASS_HASH VARCHAR(255) NOT NULL
);

-- Tabla de Usuarios Principales
CREATE TABLE USUARIO (
    USUARIO_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SALDO DECIMAL(10, 2) DEFAULT 0.00 CHECK (SALDO >= 0), -- Evita saldos negativos
	PASS_HASH VARCHAR(255) NOT NULL
);

-- Tabla de Clanes
CREATE TABLE CLAN (
    CLAN_ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    IMAGE_URL VARCHAR(255)
);

-- /------------------------------------------------------------------------------------
-- Cuentas externas (Steam/Dota 2/Valorant)
CREATE TABLE GAME_ACCOUNT (
    GAME_ACCOUNT_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
	JUEGO VARCHAR(50) NOT NULL,
    PROFILE_URL VARCHAR(255),
    ID_EXTERNO VARCHAR(100), -- SteamID o RiotID
    ID_EXTERNO_2 VARCHAR(100)
);

-- Estadísticas internas de la plataforma
CREATE TABLE USUARIO_STATS (
    USER_STAT_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    JUEGO VARCHAR(50), -- 'DOTA2' o 'VALORANT'
    ELO_MMR INT DEFAULT 0,
    WINS INT DEFAULT 0,
    LOSES INT DEFAULT 0,
    RANGO_MEDALLA VARCHAR(50)
);

COMMENT ON COLUMN USUARIO_STATS.ELO_MMR IS 'ELO QUE TIENE EL USUARIO DE LA WEB';
COMMENT ON COLUMN USUARIO_STATS.JUEGO IS 'ES LA ESTADISTICA DEL JUEGO';

-- /------------------------------------------------------------------------------------
-- Salas creadas por Administradores
CREATE TABLE SALA (
    SALA_ID SERIAL PRIMARY KEY,
    ADMINISTRADOR_ID INT REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID),
    COMISION DECIMAL(10, 2) NOT NULL, -- GANANCIA DE LA SALA
    CUOTA_INICIAL DECIMAL(10, 2) NOT NULL,
    JUEGO VARCHAR(50), -- SEA DOTA O VALORANT, ETC
    ESTADO VARCHAR(20) DEFAULT 'ABIERTA', -- ABIERTA, EN_JUEGO, FINALIZADA
    MMR_MIN INT, -- GANANCIA DE LA SALA
    MMR_MAX INT,
    EQUIPO_GANADOR VARCHAR(1), -- 'A' o 'B'
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN SALA.COMISION IS 'ES LA GANANCIA DE LA SALA, LO QUE GANA LA CASA';
COMMENT ON COLUMN SALA.CUOTA_INICIAL IS 'MINIMO DE INGRESO PARA LA SALA';
COMMENT ON COLUMN SALA.JUEGO IS 'JUEGO DONDE SE VA A REALIZAR LA SALA';
COMMENT ON COLUMN SALA.MMR_MIN IS 'MMR MINIMO PARA QUE INGRESEN A LA SALA';
COMMENT ON COLUMN SALA.MMR_MAX IS 'MMR MAXIMO PARA QUE INGRESEN A LA SALA';

-- Tabla Intermedia de Jugadores en Sala (Muchos a Muchos)
CREATE TABLE INTERACTUA (
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    SALA_ID INT REFERENCES SALA(SALA_ID),
    MONTO_PAGADO DECIMAL(10, 2),
    ROL VARCHAR(50),
    EQUIPO VARCHAR(1), -- 'A' o 'B'
    PRIMARY KEY (USUARIO_ID, SALA_ID)
);

-- /------------------------------------------------------------------------------------
-- Solicitudes de Recarga
CREATE TABLE SOLICITUD_RECARGA (
    RECARGA_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    ADMINISTRADOR_ID INT REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID), -- Quien aprueba
    MONTO DECIMAL(10, 2) NOT NULL,
    PLATAFORMA VARCHAR(50) NOT NULL, -- Yape, Plin, etc.
    CUENTA_DESTINO VARCHAR(100),
    ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
	FECHA_EMISION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_APROBACION TIMESTAMP
);

COMMENT ON COLUMN SOLICITUD_RECARGA.CUENTA_DESTINO IS 'CUENTA INTERBANCARIA DE SER EL CASO';

-- Solicitudes de Retiro
CREATE TABLE SOLICITUD_RETIRO (
    RETIRO_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    ADMINISTRADOR_ID INT REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID), -- Quien paga
    MONTO DECIMAL(10, 2) NOT NULL CHECK (MONTO >= 20), -- Tu regla de negocio
    PLATAFORMA VARCHAR(50) NOT NULL,
    CUENTA_DESTINO VARCHAR(100),
    URL_IMAGEN VARCHAR(255), -- Captura del Yape enviado
    ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
	FECHA_EMISION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_RETIRO TIMESTAMP
);

COMMENT ON COLUMN SOLICITUD_RETIRO.CUENTA_DESTINO IS 'CUENTA INTERBANCARIA DE SER EL CASO';
COMMENT ON COLUMN SOLICITUD_RETIRO.URL_IMAGEN IS 'CAPTURA DE PAGO';

-- Historial de Movimientos de Saldo
CREATE TABLE MOVIMIENTOS (
    MOVIMIENTO_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
	RECARGA_ID INT REFERENCES SOLICITUD_RECARGA(RECARGA_ID),
	RETIRO_ID INT REFERENCES SOLICITUD_RETIRO(RETIRO_ID),
	SALA_ID INT REFERENCES SALA(SALA_ID),
    TIPO VARCHAR(20) NOT NULL, -- 'INGRESO', 'EGRESO'
    MONTO DECIMAL(10, 2) NOT NULL,
    CONCEPTO TEXT NOT NULL, -- Ej: 'Premio Sala #10' o 'Recarga Yape'
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Coalesce para movimientos fk nulleables
-- En esa parte si es solamente recarga se tiene registro
-- En esa parte si es solamente retiro se tiene registro
-- En esa parte si se gasta en una sala se tiene registro
ALTER TABLE MOVIMIENTOS 
ADD CONSTRAINT CHK_MOVIMIENTO_ORIGEN
CHECK (
    (RECARGA_ID IS NOT NULL AND SALA_ID IS NULL AND RETIRO_ID IS NULL) OR
    (RECARGA_ID IS NULL AND SALA_ID IS NOT NULL AND RETIRO_ID IS NULL) OR
    (RECARGA_ID IS NULL AND SALA_ID IS NULL AND RETIRO_ID IS NOT NULL)
);

COMMENT ON COLUMN MOVIMIENTOS.CONCEPTO IS 'REGISTRO DEL MOVIMIENTO';

-- Gestión de Baneos
CREATE TABLE BANEO (
    BANEO_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    ADMINISTRADOR_ID INT REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID),
    MOTIVO TEXT NOT NULL,
    TIEMPO INT NOT NULL, -- Duración en horas
    FECHA_BANEO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- /------------------------------------------------------------------------------------
