-- ==========================================================
-- 0. LIMPIEZA DE BASE DE DATOS (DROPS)
-- ==========================================================
DROP TABLE IF EXISTS LOG_ACCIONES CASCADE;
DROP TABLE IF EXISTS BANEO CASCADE;
DROP TABLE IF EXISTS MOVIMIENTOS CASCADE;
DROP TABLE IF EXISTS SOLICITUD_RETIRO CASCADE;
DROP TABLE IF EXISTS SOLICITUD_RECARGA CASCADE;
DROP TABLE IF EXISTS PARTICIPANTE_SALA CASCADE;
DROP TABLE IF EXISTS SALA CASCADE;
DROP TABLE IF EXISTS TORNEO CASCADE;
DROP TABLE IF EXISTS MAPA CASCADE;
DROP TABLE IF EXISTS HISTORIAL_MMR_ADMIN CASCADE;
DROP TABLE IF EXISTS USUARIO_STATS CASCADE;
DROP TABLE IF EXISTS GAME_ACCOUNT CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS CLAN CASCADE;

-- ==========================================================
-- 1. USUARIOS, ROLES Y CLANES
-- ==========================================================
CREATE TABLE CLAN (
    CLAN_ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    IMAGE_URL VARCHAR(255)
);

CREATE TABLE USUARIO (
    USUARIO_ID SERIAL PRIMARY KEY,
    CLAN_ID INT REFERENCES CLAN(CLAN_ID),
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    AP_PATERNO VARCHAR(100) NOT NULL,
    AP_MATERNO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASS_HASH TEXT NOT NULL,
	SALDO_RECARGA NUMERIC(18,2) NOT NULL DEFAULT 0,
    SALDO_REAL DECIMAL(10, 2) DEFAULT 0.00 CHECK (SALDO_REAL >= 0),
    SALDO_BONO DECIMAL(10, 2) DEFAULT 0.00 CHECK (SALDO_BONO >= 0),
    ROL VARCHAR(20) DEFAULT 'USER', 
    PARTIDAS_JUGADAS INT DEFAULT 0, 
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 2. CUENTAS Y ESTADÍSTICAS DE JUEGO
-- ==========================================================
CREATE TABLE GAME_ACCOUNT (
    GAME_ACCOUNT_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    JUEGO VARCHAR(50) NOT NULL, -- 'VALORANT' o 'DOTA2'
    ID_EXTERNO VARCHAR(100) NOT NULL, 
    ID_VISIBLE VARCHAR(100), 
    RANGO_ACTUAL VARCHAR(50), 
    ES_RANGO_MANUAL BOOLEAN DEFAULT FALSE,
    FECHA_VINCULACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_USUARIO_JUEGO UNIQUE(USUARIO_ID, JUEGO) 
);

CREATE TABLE USUARIO_STATS (
    USER_STAT_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    JUEGO VARCHAR(50), 
    ELO_MMR INT DEFAULT 0,
    WINS INT DEFAULT 0,
    LOSES INT DEFAULT 0,
    RANGO_MEDALLA VARCHAR(50)
);

CREATE TABLE HISTORIAL_MMR_ADMIN (
    HISTORIAL_ID SERIAL PRIMARY KEY,
    ADMIN_ID INT REFERENCES USUARIO(USUARIO_ID),
    USER_STAT_ID INT REFERENCES USUARIO_STATS(USER_STAT_ID),
    MMR_ANTERIOR INT NOT NULL,
    MMR_NUEVO INT NOT NULL,
    MOTIVO TEXT NOT NULL, 
    FECHA_CAMBIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 3. INFRAESTRUCTURA DE PARTIDAS (SALA INTEGRADA CON V5.1)
-- ==========================================================
CREATE TABLE MAPA (
    MAPA_ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
    IMAGEN_URL TEXT,
    ACTIVO BOOLEAN DEFAULT TRUE 
);

CREATE TABLE TORNEO (
    TORNEO_ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL, 
    PREMIO_POZO DECIMAL(10, 2) NOT NULL,
    COSTO_INSCRIPCION DECIMAL(10, 2) NOT NULL,
    ESTADO VARCHAR(20) DEFAULT 'REGISTRO', 
    FECHA_INICIO TIMESTAMP,
    FECHA_FIN TIMESTAMP
);

CREATE TABLE SALA (
    SALA_ID SERIAL PRIMARY KEY,
    CREADOR_ID INT REFERENCES USUARIO(USUARIO_ID), 
    TORNEO_ID INT REFERENCES TORNEO(TORNEO_ID), 
    NOMBRE VARCHAR(100), 
    TIPO_SALA VARCHAR(50) DEFAULT 'BASICA', 
    JUEGO VARCHAR(50) NOT NULL, 

    -- ECONOMÍA DE LA SALA
    COSTO_ENTRADA DECIMAL(10, 2) NOT NULL, 
    PREMIO_A_REPARTIR DECIMAL(10, 2) NOT NULL,
    GANANCIA_PLATAFORMA DECIMAL(10, 2) NOT NULL, 
    
    ESTADO VARCHAR(20) DEFAULT 'ESPERANDO', 
    
    -- MAP VETO LOGIC
    MAPA_ELEGIDO_ID INT REFERENCES MAPA(MAPA_ID),
    VETO_LOG JSONB, 
    
    RESULTADO_GANADOR VARCHAR(20), 
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- NUEVOS CAMPOS VERSION 5.1
    mmr_minimo INTEGER NOT NULL DEFAULT 0,
    mmr_maximo INTEGER NOT NULL DEFAULT 10000,
    "Formato" VARCHAR(50) DEFAULT '1v1',
    "Capitan1Id" INTEGER NULL,
    "Capitan2Id" INTEGER NULL,
    "GanadorSorteoId" INTEGER NULL,
    "TurnoActualId" INTEGER NULL,
    nombrelobby TEXT,
    passwordlobby TEXT
);

CREATE TABLE PARTICIPANTE_SALA (
    PARTICIPACION_ID SERIAL PRIMARY KEY,
    SALA_ID INT REFERENCES SALA(SALA_ID),
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    GAME_ACCOUNT_ID INT REFERENCES GAME_ACCOUNT(GAME_ACCOUNT_ID), 
    
    -- Tipo ampliado a 50 de la V5.1
    EQUIPO VARCHAR(50) NOT NULL, -- Ej: 'A', 'B', 'ESPERANDO_DRAFT'
    
    ES_CAPITAN BOOLEAN DEFAULT FALSE, 
    SLOT_INDEX INT, 
    
    PAGO_CON_BONO DECIMAL(10, 2) DEFAULT 0,
    PAGO_CON_REAL DECIMAL(10, 2) DEFAULT 0,
    
    CONSTRAINT UQ_SALA_SLOT UNIQUE(SALA_ID, SLOT_INDEX) 
);

-- ==========================================================
-- 4. FLUJO FINANCIERO Y MOVIMIENTOS
-- ==========================================================
CREATE TABLE SOLICITUD_RECARGA (
    RECARGA_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    MONTO DECIMAL(10, 2) NOT NULL CHECK (MONTO > 0),
    MONEDA VARCHAR(10) DEFAULT 'PEN',
    METODO VARCHAR(50), 
    CUENTA_DESTINO VARCHAR(100),
    NRO_OPERACION VARCHAR(100),
    ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
    ADMIN_ATENDIENDO_ID INT REFERENCES USUARIO(USUARIO_ID), 
    FECHA_EMISION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_CIERRE TIMESTAMP
);

CREATE TABLE SOLICITUD_RETIRO (
    RETIRO_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    MONTO DECIMAL(10, 2) NOT NULL CHECK (MONTO >= 20.00),
    MONEDA VARCHAR(10) DEFAULT 'PEN',
    METODO VARCHAR(50) NOT NULL,
    CUENTA_DESTINO TEXT NOT NULL,
    NRO_OPERACION VARCHAR(100),
    ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
    ADMIN_ATENDIENDO_ID INT REFERENCES USUARIO(USUARIO_ID),
    FECHA_EMISION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_PAGO TIMESTAMP
);

CREATE TABLE MOVIMIENTOS (
    MOVIMIENTO_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    RECARGA_ID INT REFERENCES SOLICITUD_RECARGA(RECARGA_ID),
    RETIRO_ID INT REFERENCES SOLICITUD_RETIRO(RETIRO_ID),
    SALA_ID INT REFERENCES SALA(SALA_ID),
    
    -- Tipo ampliado a 50 de la V5.1
    TIPO VARCHAR(50) NOT NULL, 
    
    MONTO_REAL DECIMAL(10, 2) DEFAULT 0.00 NOT NULL,
    MONTO_BONO DECIMAL(10, 2) DEFAULT 0.00 NOT NULL,
    CONCEPTO TEXT NOT NULL, 
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_MOVIMIENTO_ORIGEN CHECK (
        (RECARGA_ID IS NOT NULL AND SALA_ID IS NULL AND RETIRO_ID IS NULL) OR
        (RECARGA_ID IS NULL AND SALA_ID IS NOT NULL AND RETIRO_ID IS NULL) OR
        (RECARGA_ID IS NULL AND SALA_ID IS NULL AND RETIRO_ID IS NOT NULL) OR
        (RECARGA_ID IS NULL AND SALA_ID IS NULL AND RETIRO_ID IS NULL)
    )
);

-- ==========================================================
-- 5. AUDITORÍA Y SEGURIDAD
-- ==========================================================
CREATE TABLE BANEO (
    BANEO_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    ADMIN_ID INT REFERENCES USUARIO(USUARIO_ID),
    MOTIVO TEXT NOT NULL,
    TIEMPO INT NOT NULL, 
    FECHA_BANEO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOG_ACCIONES (
    LOG_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID), 
    ACCION VARCHAR(50), 
    DETALLE JSONB, 
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 6. DATOS DE PRUEBA / AJUSTES INICIALES (De V5.1)
-- ==========================================================
-- Nota: Asegúrate de que existan los IDs de usuario 13 y 14 y la sala 17 antes de ejecutar esto, 
-- o comenta estas líneas si es una instalación limpia.
-- UPDATE sala 
-- SET "Capitan1Id" = 13, "Capitan2Id" = 14, "TurnoActualId" = 13, estado = 'SORTEO'
-- WHERE sala_id = 17;