-- ==========================================================
-- 0. LIMPIEZA DE BASE DE DATOS (DROPS)
-- Ejecutar en orden inverso a la creación para evitar errores de Foreign Key
-- ==========================================================
DROP TABLE IF EXISTS LOG_ACCIONES CASCADE;
DROP TABLE IF EXISTS BANEO CASCADE;
DROP TABLE IF EXISTS MOVIMIENTOS CASCADE;
DROP TABLE IF EXISTS SOLICITUD_RETIRO CASCADE;
DROP TABLE IF EXISTS SOLICITUD_RECARGA CASCADE;
DROP TABLE IF EXISTS PARTICIPANTE_SALA CASCADE;
DROP TABLE IF EXISTS SALA CASCADE;
DROP TABLE IF EXISTS TORNEO CASCADE;
DROP TABLE IF EXISTS MAPA CASCADE;
DROP TABLE IF EXISTS HISTORIAL_MMR_ADMIN CASCADE;
DROP TABLE IF EXISTS USUARIO_STATS CASCADE;
DROP TABLE IF EXISTS GAME_ACCOUNT CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS CLAN CASCADE;

-- ==========================================================
-- 1. USUARIOS, ROLES Y CLANES
-- ==========================================================
CREATE TABLE CLAN (
    CLAN_ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    IMAGE_URL VARCHAR(255)
);

CREATE TABLE USUARIO (
    USUARIO_ID SERIAL PRIMARY KEY,
    CLAN_ID INT REFERENCES CLAN(CLAN_ID), -- Integrado del V2
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASS_HASH TEXT NOT NULL,
    
    -- BILLETERA DOBLE (Dinero Real vs Bono)
    SALDO_REAL DECIMAL(10, 2) DEFAULT 0.00 CHECK (SALDO_REAL >= 0),
    SALDO_BONO DECIMAL(10, 2) DEFAULT 0.00 CHECK (SALDO_BONO >= 0),
    
    -- ROLES: 'SUPERADMIN', 'HOST', 'USER'
    ROL VARCHAR(20) DEFAULT 'USER', 
    
    -- CANDADO DE SEGURIDAD PARA RETIROS
    PARTIDAS_JUGADAS INT DEFAULT 0, 
    
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 2. CUENTAS Y ESTADÍSTICAS DE JUEGO
-- ==========================================================
CREATE TABLE GAME_ACCOUNT (
    GAME_ACCOUNT_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    
    JUEGO VARCHAR(50) NOT NULL, -- 'VALORANT' o 'DOTA2'
    ID_EXTERNO VARCHAR(100) NOT NULL, 
    ID_VISIBLE VARCHAR(100), 
    
    RANGO_ACTUAL VARCHAR(50), 
    ES_RANGO_MANUAL BOOLEAN DEFAULT FALSE,
    FECHA_VINCULACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- REGLA CLAVE: Un usuario puede tener 1 cuenta de Valorant Y 1 de Dota.
    CONSTRAINT UQ_USUARIO_JUEGO UNIQUE(USUARIO_ID, JUEGO) 
);

CREATE TABLE USUARIO_STATS (
    USER_STAT_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    JUEGO VARCHAR(50), -- 'DOTA2' o 'VALORANT'
    ELO_MMR INT DEFAULT 0,
    WINS INT DEFAULT 0,
    LOSES INT DEFAULT 0,
    RANGO_MEDALLA VARCHAR(50)
);

-- (LA LÍNEA ROJA DEL V2) Auditoría de Smurfs
CREATE TABLE HISTORIAL_MMR_ADMIN (
    HISTORIAL_ID SERIAL PRIMARY KEY,
    ADMIN_ID INT REFERENCES USUARIO(USUARIO_ID), -- Quien aplicó la sanción
    USER_STAT_ID INT REFERENCES USUARIO_STATS(USER_STAT_ID), -- A qué stat afectó
    MMR_ANTERIOR INT NOT NULL,
    MMR_NUEVO INT NOT NULL,
    MOTIVO TEXT NOT NULL, 
    FECHA_CAMBIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 3. INFRAESTRUCTURA DE PARTIDAS
-- ==========================================================
CREATE TABLE MAPA (
    MAPA_ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
    IMAGEN_URL TEXT,
    ACTIVO BOOLEAN DEFAULT TRUE 
);

CREATE TABLE TORNEO (
    TORNEO_ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL, 
    PREMIO_POZO DECIMAL(10, 2) NOT NULL,
    COSTO_INSCRIPCION DECIMAL(10, 2) NOT NULL,
    ESTADO VARCHAR(20) DEFAULT 'REGISTRO', 
    FECHA_INICIO TIMESTAMP,
    FECHA_FIN TIMESTAMP
);

CREATE TABLE SALA (
    SALA_ID SERIAL PRIMARY KEY,
    CREADOR_ID INT REFERENCES USUARIO(USUARIO_ID), 
    TORNEO_ID INT REFERENCES TORNEO(TORNEO_ID), 
    
    NOMBRE VARCHAR(100), 
    TIPO_SALA VARCHAR(50) DEFAULT 'BASICA', 
    JUEGO VARCHAR(50) NOT NULL, 

    -- ECONOMÍA DE LA SALA
    COSTO_ENTRADA DECIMAL(10, 2) NOT NULL, 
    PREMIO_A_REPARTIR DECIMAL(10, 2) NOT NULL,
    GANANCIA_PLATAFORMA DECIMAL(10, 2) NOT NULL, 
    
    ESTADO VARCHAR(20) DEFAULT 'ESPERANDO', 
    
    -- MAP VETO LOGIC
    MAPA_ELEGIDO_ID INT REFERENCES MAPA(MAPA_ID),
    VETO_LOG JSONB, 
    
    RESULTADO_GANADOR VARCHAR(20), 
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PARTICIPANTE_SALA (
    PARTICIPACION_ID SERIAL PRIMARY KEY,
    SALA_ID INT REFERENCES SALA(SALA_ID),
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    GAME_ACCOUNT_ID INT REFERENCES GAME_ACCOUNT(GAME_ACCOUNT_ID), 
    
    EQUIPO VARCHAR(10) NOT NULL, -- 'A' o 'B'
    ES_CAPITAN BOOLEAN DEFAULT FALSE, 
    SLOT_INDEX INT, -- 0-4 (Equipo A), 5-9 (Equipo B)
    
    PAGO_CON_BONO DECIMAL(10, 2) DEFAULT 0,
    PAGO_CON_REAL DECIMAL(10, 2) DEFAULT 0,
    
    CONSTRAINT UQ_SALA_SLOT UNIQUE(SALA_ID, SLOT_INDEX) 
);

-- ==========================================================
-- 4. FLUJO FINANCIERO Y MOVIMIENTOS
-- ==========================================================
CREATE TABLE SOLICITUD_RECARGA (
    RECARGA_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    MONTO DECIMAL(10, 2) NOT NULL CHECK (MONTO > 0),
    METODO VARCHAR(50), 
    CODIGO_OPERACION VARCHAR(100), 
    FOTO_VOUCHER_URL TEXT, 
    
    ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
    ADMIN_ATENDIENDO_ID INT REFERENCES USUARIO(USUARIO_ID), 
    
    FECHA_EMISION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_CIERRE TIMESTAMP
);

CREATE TABLE SOLICITUD_RETIRO (
    RETIRO_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    MONTO DECIMAL(10, 2) NOT NULL CHECK (MONTO >= 20.00),
    CUENTA_DESTINO TEXT NOT NULL,
    
    ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
    ADMIN_ATENDIENDO_ID INT REFERENCES USUARIO(USUARIO_ID),
    
    FOTO_CONSTANCIA_PAGO TEXT, 
    FECHA_EMISION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_PAGO TIMESTAMP
);

-- EL LIBRO MAYOR (Actualizado para Doble Billetera)
CREATE TABLE MOVIMIENTOS (
    MOVIMIENTO_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID),
    
    -- Arcos Exclusivos
    RECARGA_ID INT REFERENCES SOLICITUD_RECARGA(RECARGA_ID),
    RETIRO_ID INT REFERENCES SOLICITUD_RETIRO(RETIRO_ID),
    SALA_ID INT REFERENCES SALA(SALA_ID),
    
    TIPO VARCHAR(20) NOT NULL, -- 'INGRESO', 'EGRESO'
    
    -- Separación de saldos para auditoría exacta
    MONTO_REAL DECIMAL(10, 2) DEFAULT 0.00 NOT NULL,
    MONTO_BONO DECIMAL(10, 2) DEFAULT 0.00 NOT NULL,
    
    CONCEPTO TEXT NOT NULL, 
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT CHK_MOVIMIENTO_ORIGEN CHECK (
        (RECARGA_ID IS NOT NULL AND SALA_ID IS NULL AND RETIRO_ID IS NULL) OR
        (RECARGA_ID IS NULL AND SALA_ID IS NOT NULL AND RETIRO_ID IS NULL) OR
        (RECARGA_ID IS NULL AND SALA_ID IS NULL AND RETIRO_ID IS NOT NULL)
    )
);

-- ==========================================================
-- 5. AUDITORÍA Y SEGURIDAD
-- ==========================================================
CREATE TABLE BANEO (
    BANEO_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID), -- Usuario castigado
    ADMIN_ID INT REFERENCES USUARIO(USUARIO_ID), -- Admin que castiga
    MOTIVO TEXT NOT NULL,
    TIEMPO INT NOT NULL, -- Duración en horas
    FECHA_BANEO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOG_ACCIONES (
    LOG_ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIO(USUARIO_ID), 
    ACCION VARCHAR(50), 
    DETALLE JSONB, 
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);